
apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: "manifest-2.22-71b6fa1"
  labels:
    kubean.io/sprayRelease: "2.22"
  annotations:
    kubean.io/sprayTimestamp: "1707335976"
    kubean.io/sprayRelease: "2.22"
    kubean.io/sprayCommit: "71b6fa1"
spec:
  kubesprayVersion: "71b6fa137c1ba7509dd295de54e93204d2f2feb3"
  kubeanVersion: ""
  docker:
    - os: redhat-7
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: redhat
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: debian
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: ubuntu
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: kylin
      defaultVersion: "19.03"
      versionRange:
        - "18.09"
        - "19.03"
  components:
    - name: cilium
      defaultVersion: "v1.13.0"
      versionRange: []
    - name: flannel
      defaultVersion: "v0.21.4"
      versionRange: []
    - name: kube_ovn
      defaultVersion: "v1.10.7"
      versionRange: []
    - name: runc
      defaultVersion: "v1.1.12"
      versionRange:
        - "v1.1.12"
        - "v1.1.11"
        - "v1.1.10"
        - "v1.1.9"
        - "v1.1.8"
        - "v1.1.7"
        - "v1.1.6"
        - "v1.1.5"
        - "v1.1.4"
        - "v1.1.3"
        - "v1.1.2"
        - "v1.1.1"
        - "v1.1.0"
    - name: kube
      defaultVersion: "v1.26.13"
      versionRange:
        - "v1.26.11"
        - "v1.26.10"
        - "v1.26.9"
        - "v1.26.8"
        - "v1.26.7"
        - "v1.26.6"
        - "v1.26.5"
        - "v1.26.4"
        - "v1.26.3"
        - "v1.26.2"
        - "v1.26.1"
        - "v1.26.0"
        - "v1.25.14"
        - "v1.25.13"
        - "v1.25.12"
        - "v1.25.11"
        - "v1.25.10"
        - "v1.25.9"
        - "v1.25.8"
        - "v1.25.7"
        - "v1.25.6"
        - "v1.25.5"
        - "v1.25.4"
        - "v1.25.3"
        - "v1.25.2"
        - "v1.25.1"
        - "v1.25.0"
        - "v1.24.14"
        - "v1.24.13"
        - "v1.24.12"
        - "v1.24.11"
        - "v1.24.10"
        - "v1.24.9"
        - "v1.24.8"
        - "v1.24.7"
        - "v1.24.6"
        - "v1.24.5"
        - "v1.24.4"
        - "v1.24.3"
        - "v1.24.2"
        - "v1.24.1"
        - "v1.24.0"
        - "v1.24.15"
        - "v1.24.16"
        - "v1.24.17"
        - "v1.26.12"
        - "v1.26.13"
        - "v1.25.15"
        - "v1.25.16"
    - name: cni
      defaultVersion: "v1.3.0"
      versionRange:
        - "v1.0.1"
        - "v1.1.1"
        - "v1.2.0"
        - "v1.3.0"
    - name: calico
      defaultVersion: "v3.25.1"
      versionRange:
        - "v3.25.1"
        - "v3.25.0"
        - "v3.24.6"
        - "v3.24.5"
        - "v3.23.3"
        - "v3.22.4"
    - name: containerd
      defaultVersion: "1.7.13"
      versionRange:
        - "1.7.13"
        - "1.7.12"
        - "1.7.11"
        - "1.7.10"
        - "1.7.9"
        - "1.7.8"
        - "1.7.7"
        - "1.7.6"
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
        - "1.6.28"
        - "1.6.27"
        - "1.6.26"
        - "1.6.25"
        - "1.6.24"
        - "1.6.23"
        - "1.6.22"
        - "1.6.21"
        - "1.6.20"
        - "1.6.19"
        - "1.6.18"
        - "1.6.17"
        - "1.6.16"
        - "1.6.15"
        - "1.6.14"
        - "1.6.13"
        - "1.6.12"
        - "1.6.11"
        - "1.6.10"
        - "1.6.9"
        - "1.6.8"
        - "1.6.7"
        - "1.6.6"
        - "1.6.5"
        - "1.6.4"
        - "1.6.3"
        - "1.6.2"
        - "1.6.1"
        - "1.6.0"
        - "1.5.18"
        - "1.5.17"
        - "1.5.16"
        - "1.5.15"
        - "1.5.14"
        - "1.5.13"
        - "1.5.12"
        - "1.5.11"
        - "1.5.10"
        - "1.5.9"
        - "1.5.8"
        - "1.5.7"
        - "1.5.5"
