
apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: "manifest-2.24-bc6bd21"
  labels:
    kubean.io/sprayRelease: "2.24"
  annotations:
    kubean.io/sprayTimestamp: "1709827149"
    kubean.io/sprayRelease: "2.24"
    kubean.io/sprayCommit: "bc6bd21"
spec:
  kubesprayVersion: "bc6bd21ab399ddc86d60ca440cae4f0b6ec9e636"
  kubeanVersion: ""
  docker:
    - os: redhat-7
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: redhat
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: debian
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: ubuntu
      defaultVersion: "20.10"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
    - os: kylin
      defaultVersion: "19.03"
      versionRange:
        - "18.09"
        - "19.03"
  components:
    - name: cilium
      defaultVersion: "v1.13.4"
      versionRange: []
    - name: flannel
      defaultVersion: "v0.22.0"
      versionRange: []
    - name: kube_ovn
      defaultVersion: "v1.11.5"
      versionRange: []
    - name: runc
      defaultVersion: "v1.1.12"
      versionRange:
        - "v1.1.12"
        - "v1.1.11"
        - "v1.1.10"
        - "v1.1.9"
        - "v1.1.8"
        - "v1.1.7"
        - "v1.1.6"
        - "v1.1.5"
        - "v1.1.4"
        - "v1.1.3"
    - name: kube
      defaultVersion: "v1.28.6"
      versionRange:
        - "v1.29.1"
        - "v1.29.0"
        - "v1.28.6"
        - "v1.28.5"
        - "v1.28.4"
        - "v1.28.3"
        - "v1.28.2"
        - "v1.28.1"
        - "v1.28.0"
        - "v1.27.10"
        - "v1.27.9"
        - "v1.27.8"
        - "v1.27.7"
        - "v1.27.6"
        - "v1.27.5"
        - "v1.27.4"
        - "v1.27.3"
        - "v1.27.2"
        - "v1.27.1"
        - "v1.27.0"
        - "v1.26.13"
        - "v1.26.12"
        - "v1.26.11"
        - "v1.26.10"
        - "v1.26.9"
        - "v1.26.8"
        - "v1.26.7"
        - "v1.26.6"
        - "v1.26.5"
        - "v1.26.4"
        - "v1.26.3"
        - "v1.26.2"
        - "v1.26.1"
        - "v1.26.0"
    - name: cni
      defaultVersion: "v1.3.0"
      versionRange:
        - "v1.3.0"
        - "v1.2.0"
        - "v1.1.1"
        - "v1.1.0"
        - "v1.0.1"
        - "v1.0.0"
        - "v0.9.1"
    - name: calico
      defaultVersion: "v3.26.4"
      versionRange:
        - "v3.26.4"
        - "v3.26.3"
        - "v3.26.2"
        - "v3.26.1"
        - "v3.26.0"
        - "v3.25.2"
        - "v3.25.1"
        - "v3.25.0"
        - "v3.24.6"
        - "v3.24.5"
        - "v3.24.4"
        - "v3.24.3"
        - "v3.24.2"
        - "v3.24.1"
        - "v3.24.0"
        - "v3.23.5"
        - "v3.23.4"
        - "v3.23.3"
        - "v3.23.2"
        - "v3.23.1"
        - "v3.23.0"
        - "v3.22.5"
        - "v3.22.4"
        - "v3.22.3"
    - name: containerd
      defaultVersion: "1.7.13"
      versionRange:
        - "1.7.13"
        - "1.7.12"
        - "1.7.11"
        - "1.7.10"
        - "1.7.9"
        - "1.7.8"
        - "1.7.7"
        - "1.7.6"
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
        - "1.6.28"
        - "1.6.27"
        - "1.6.26"
        - "1.6.25"
        - "1.6.24"
        - "1.6.23"
        - "1.6.22"
        - "1.6.21"
        - "1.6.20"
        - "1.6.19"
        - "1.6.18"
        - "1.6.17"
        - "1.6.16"
        - "1.6.15"
        - "1.6.14"
        - "1.6.13"
        - "1.6.12"
        - "1.6.11"
        - "1.6.10"
        - "1.6.9"
        - "1.6.8"
        - "1.6.7"
        - "1.6.6"
        - "1.6.5"
        - "1.6.4"
        - "1.6.3"
        - "1.6.2"
        - "1.6.1"
        - "1.6.0"
        - "1.5.18"
        - "1.5.17"
        - "1.5.16"
        - "1.5.15"
        - "1.5.14"
