
apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: "manifest-2.27-45140b5"
  labels:
    kubean.io/sprayRelease: "2.27"
  annotations:
    kubean.io/sprayTimestamp: "1751032833"
    kubean.io/sprayRelease: "2.27"
    kubean.io/sprayCommit: "45140b5"
    helm.sh/resource-policy: keep
spec:
  kubesprayVersion: "45140b558266014296ddc6075b0518662a4d4cbe"
  kubeanVersion: ""
  docker:
    - os: redhat
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
    - os: debian
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "25.0"
        - "26.0"
        - "26.1"
    - os: ubuntu
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
    - os: kylin
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
  components:
    - name: cilium
      defaultVersion: "v1.15.9"
      versionRange: []
    - name: flannel
      defaultVersion: "v0.22.0"
      versionRange: []
    - name: kube_ovn
      defaultVersion: "v1.12.21"
      versionRange: []
    - name: runc
      defaultVersion: "v1.2.6"
      versionRange:
        - "v1.2.6"
        - "v1.2.5"
        - "v1.2.4"
        - "v1.2.3"
        - "v1.2.2"
        - "v1.2.1"
        - "v1.2.0"
        - "v1.1.15"
        - "v1.1.14"
        - "v1.1.13"
        - "v1.1.12"
        - "v1.1.11"
        - "v1.1.10"
        - "v1.1.9"
        - "v1.1.8"
    - name: kube
      defaultVersion: "v1.31.9"
      versionRange:
        - "v1.31.9"
        - "v1.31.8"
        - "v1.31.7"
        - "v1.31.6"
        - "v1.31.5"
        - "v1.31.4"
        - "v1.31.3"
        - "v1.31.2"
        - "v1.31.1"
        - "v1.31.0"
        - "v1.30.13"
        - "v1.30.12"
        - "v1.30.11"
        - "v1.30.10"
        - "v1.30.9"
        - "v1.30.8"
        - "v1.30.7"
        - "v1.30.6"
        - "v1.30.5"
        - "v1.30.4"
        - "v1.30.3"
        - "v1.30.2"
        - "v1.30.1"
        - "v1.30.0"
        - "v1.29.15"
        - "v1.29.14"
        - "v1.29.13"
        - "v1.29.12"
        - "v1.29.11"
        - "v1.29.10"
        - "v1.29.9"
        - "v1.29.8"
        - "v1.29.7"
        - "v1.29.6"
        - "v1.29.5"
        - "v1.29.4"
        - "v1.29.3"
        - "v1.29.2"
        - "v1.29.1"
        - "v1.29.0"
    - name: cni
      defaultVersion: "v1.4.1"
      versionRange:
        - "v1.4.1"
        - "v1.4.0"
        - "v1.3.0"
        - "v1.2.0"
        - "v1.1.1"
        - "v1.1.0"
        - "v1.0.1"
        - "v1.0.0"
    - name: calico
      defaultVersion: "v3.29.4"
      versionRange:
        - "v3.29.4"
        - "v3.29.3"
        - "v3.29.2"
        - "v3.29.1"
        - "v3.29.0"
        - "v3.28.4"
        - "v3.28.3"
        - "v3.28.2"
        - "v3.28.1"
        - "v3.28.0"
        - "v3.27.5"
        - "v3.27.4"
        - "v3.27.3"
        - "v3.27.2"
        - "v3.27.1"
        - "v3.27.0"
        - "v3.26.5"
        - "v3.26.4"
        - "v3.26.3"
        - "v3.26.2"
        - "v3.26.1"
        - "v3.26.0"
        - "v3.25.2"
    - name: containerd
      defaultVersion: "1.7.27"
      versionRange:
        - "1.7.27"
        - "1.7.26"
        - "1.7.25"
        - "1.7.24"
        - "1.7.23"
        - "1.7.22"
        - "1.7.21"
        - "1.7.20"
        - "1.7.19"
        - "1.7.18"
        - "1.7.17"
        - "1.7.16"
        - "1.7.15"
        - "1.7.14"
        - "1.7.13"
        - "1.7.12"
        - "1.7.11"
        - "1.7.10"
        - "1.7.9"
        - "1.7.8"
        - "1.7.7"
        - "1.7.6"
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
        - "1.6.38"
        - "1.6.37"
        - "1.6.36"
        - "1.6.35"
        - "1.6.34"
        - "1.6.33"
        - "1.6.32"
        - "1.6.31"
        - "1.6.30"
        - "1.6.29"
        - "1.6.28"
        - "1.6.27"
        - "1.6.26"
        - "1.6.25"
        - "1.6.24"
        - "1.6.23"
        - "1.6.22"
        - "1.6.21"
        - "1.6.20"
        - "1.6.19"
        - "1.6.18"
        - "1.6.17"
        - "1.6.16"
        - "1.6.15"
        - "1.6.14"
